### ISSUE TITLE
PHP 8 and ReflectionUnionType

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/form#103]
Good day. I have many search forms extended from FormModel and when i using union attribute type (like `public int|array|null $source_ids = null;`) it fails, because type of this property is instance of `ReflectionUnionType` not `ReflectionType`. Maybe property `attributes` do as `attributes[name] = [...types]`?

**Comment by samdark** [comment]
Doesn't seem to be a good idea to vary input types like that or to use inheritance. Validation should be definitive.
