### ISSUE TITLE
Wrong html input pattern for Url::rule

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/form#149]
Good day. When i set `Url::rule` to `FormModel` it also generate input pattern attribute equals `^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])`. But it's wrong for browser if input value has only domain. Nevertheless - if i remove pattern attribute using browser console and send form, validation will be valid. Thanks

![2021-11-08 19 04 13 localhost efe762fb827e](https://user-images.githubusercontent.com/90403480/140777155-82eef68e-87c4-4570-8ea9-948f11c79eed.jpg)
![2021-11-08 19 04 52 localhost 4fa8c3965d78](https://user-images.githubusercontent.com/90403480/140777163-7b0f12bf-d764-4191-be2c-4eff7804696c.jpg)

**Comment by terabytesoftw** [comment]
You can show me your code, since it works perfect for me.

![image](https://user-images.githubusercontent.com/42547589/140780687-35ae216b-40c1-49a2-9809-1d3de0052739.png)

**Comment by Gerych1984** [comment]
> 
> You can show me your code, since it works perfect for me.



Yes, but in my case i have other pattern (with pattern like you it's works). Very interesting

`<input type="url" id="activesourceform-url" class="form-control" name="ActiveSourceForm[url]" required="" pattern="^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])">`

![2021-11-08 19 38 38 82 148 17 174 8ef91a20734d](https://user-images.githubusercontent.com/90403480/140782012-95c564f5-49e6-4f1f-b694-a9a443a59ce7.jpg)

**Comment by terabytesoftw** [comment]
> > You can show me your code, since it works perfect for me.
> 
> Yes, but in my case i have other pattern (with pattern like you it's works). Very interesting
> 
> `<input type="url" id="activesourceform-url" class="form-control" name="ActiveSourceForm[url]" required="" pattern="^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])">`
> 
> ![2021-11-08 19 38 38 82 148 17 174 8ef91a20734d](https://user-images.githubusercontent.com/90403480/140782012-95c564f5-49e6-4f1f-b694-a9a443a59ce7.jpg)

The widget does not generate the pattern, you must specify the pattern of your convenience or use the default one, so it is not a widget error.

**Comment by Gerych1984** [comment]
> > > You can show me your code, since it works perfect for me.
> > 
> > 
> > Yes, but in my case i have other pattern (with pattern like you it's works). Very interesting
> > `<input type="url" id="activesourceform-url" class="form-control" name="ActiveSourceForm[url]" required="" pattern="^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])">`
> > ![2021-11-08 19 38 38 82 148 17 174 8ef91a20734d](https://user-images.githubusercontent.com/90403480/140782012-95c564f5-49e6-4f1f-b694-a9a443a59ce7.jpg)
> 
> The widget does not generate the pattern, you must specify the pattern of your convenience or use the default one, so it is not a widget error.

I use `Url::rule` in `FormModel::getRules` with defaults. And in that rule has next pattern 

```
/**
     * @var string the regular expression used to validateValue the attribute value.
     * The pattern may contain a `{schemes}` token that will be replaced
     * by a regular expression which represents the {@see schemes()}.
     */
    private string $pattern = '/^{schemes}:\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])/i';
```

**Comment by terabytesoftw** [comment]
> > > > You can show me your code, since it works perfect for me.
> > > 
> > > 
> > > Yes, but in my case i have other pattern (with pattern like you it's works). Very interesting
> > > `<input type="url" id="activesourceform-url" class="form-control" name="ActiveSourceForm[url]" required="" pattern="^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])">`
> > > ![2021-11-08 19 38 38 82 148 17 174 8ef91a20734d](https://user-images.githubusercontent.com/90403480/140782012-95c564f5-49e6-4f1f-b694-a9a443a59ce7.jpg)
> > 
> > 
> > The widget does not generate the pattern, you must specify the pattern of your convenience or use the default one, so it is not a widget error.
> 
> I use `Url::rule` from yiisoft/validation package in `FormModel::getRules` with defaults. And in that rule has next pattern
> 
> ```
> /**
>      * @var string the regular expression used to validateValue the attribute value.
>      * The pattern may contain a `{schemes}` token that will be replaced
>      * by a regular expression which represents the {@see schemes()}.
>      */
>     private string $pattern = '/^{schemes}:\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])/i';
> ```
> 
> Maybe it rule error, not field widget



> > > > You can show me your code, since it works perfect for me.
> > > 
> > > 
> > > Yes, but in my case i have other pattern (with pattern like you it's works). Very interesting
> > > `<input type="url" id="activesourceform-url" class="form-control" name="ActiveSourceForm[url]" required="" pattern="^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])">`
> > > ![2021-11-08 19 38 38 82 148 17 174 8ef91a20734d](https://user-images.githubusercontent.com/90403480/140782012-95c564f5-49e6-4f1f-b694-a9a443a59ce7.jpg)
> > 
> > 
> > The widget does not generate the pattern, you must specify the pattern of your convenience or use the default one, so it is not a widget error.
> 
> I use `Url::rule` from yiisoft/validation package in `FormModel::getRules` with defaults. And in that rule has next pattern
> 
> ```
> /**
>      * @var string the regular expression used to validateValue the attribute value.
>      * The pattern may contain a `{schemes}` token that will be replaced
>      * by a regular expression which represents the {@see schemes()}.
>      */
>     private string $pattern = '/^{schemes}:\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)(?::\d{1,5})?(?:$|[?\/#])/i';
> ```
> 
> Maybe it rule error, not field widget

If it's a regex problem with the browser validation, if you validate it with the validator it will work, just add:

```php
<?= Form::widget()->attributes(['novalidate' => true])->begin() ?>
```

**Comment by Gerych1984** [comment]
>
> If it's a regex problem with the html validation, if you validate it with the validator it will work, just add:
> 

I think that remove validation it's "dirty hack". [Url validator](https://github.com/yiisoft/validator/blob/1287feca3f3ccf38b902b196bb774d197db23139/src/Rule/Url.php#L30) by default generate wrong pattern for input. Can you move this issue to yiisoft/validator? I think there will be more actual

**Comment by terabytesoftw** [comment]
> > If it's a regex problem with the html validation, if you validate it with the validator it will work, just add:
> 
> I think that remove validation it's "dirty hack". [Url validator](https://github.com/yiisoft/validator/blob/1287feca3f3ccf38b902b196bb774d197db23139/src/Rule/Url.php#L30) by default generate wrong pattern for input. Can you move this issue to yiisoft/validator? I think there will be more actual

I'm not telling you to do the hack, I'm just telling you that the validator without html validation works, it's a browser problem.

**Comment by Gerych1984** [comment]
> > > If it's a regex problem with the html validation, if you validate it with the validator it will work, just add:
> > 
> > 
> > I think that remove validation it's "dirty hack". [Url validator](https://github.com/yiisoft/validator/blob/1287feca3f3ccf38b902b196bb774d197db23139/src/Rule/Url.php#L30) by default generate wrong pattern for input. Can you move this issue to yiisoft/validator? I think there will be more actual
> 
> I'm not telling you to do the hack, I'm just telling you that the validator without html validation works, it's a browser problem.

But it's work with yours pattern. Maybe change default pattern in `Url::rule` or/and add some option like `$optionPattern` - i don't know. But anyway - it's not widget bug, it are validator problem

**Comment by terabytesoftw** [comment]
> > > > If it's a regex problem with the html validation, if you validate it with the validator it will work, just add:
> > > 
> > > 
> > > I think that remove validation it's "dirty hack". [Url validator](https://github.com/yiisoft/validator/blob/1287feca3f3ccf38b902b196bb774d197db23139/src/Rule/Url.php#L30) by default generate wrong pattern for input. Can you move this issue to yiisoft/validator? I think there will be more actual
> > 
> > 
> > I'm not telling you to do the hack, I'm just telling you that the validator without html validation works, it's a browser problem.
> 
> But it's work with yours pattern. Maybe change default pattern in or/and add some option like - i don't know. But anyway - it's not widget bug, it are validator problem`Url::rule``$optionPattern`

Please open the issue in the validator to solve it, thank you.

https://developer.mozilla.org/es/docs/Web/HTML/Element/form#attr-novalidate

**Comment by Gerych1984** [comment]
> > > > > If it's a regex problem with the html validation, if you validate it with the validator it will work, just add:
> > > > 
> > > > 
> > > > I think that remove validation it's "dirty hack". [Url validator](https://github.com/yiisoft/validator/blob/1287feca3f3ccf38b902b196bb774d197db23139/src/Rule/Url.php#L30) by default generate wrong pattern for input. Can you move this issue to yiisoft/validator? I think there will be more actual
> > > 
> > > 
> > > I'm not telling you to do the hack, I'm just telling you that the validator without html validation works, it's a browser problem.
> > 
> > 
> > But it's work with yours pattern. Maybe change default pattern in or/and add some option like - i don't know. But anyway - it's not widget bug, it are validator problem`` Url::rule``$optionPattern ``
> 
> Please open the issue in the validator to solve it, thank you.
> 
> https://developer.mozilla.org/es/docs/Web/HTML/Element/form#attr-novalidate

No, i meant `yiisoft/validation` url validator )) That generated wrong pattern if user set it as rule in `getRules`

**Comment by terabytesoftw** [comment]
By default it is not necessary to place the validation rule if it does not have a special validation since the input type `URL` will validate it by itself.

https://www.w3.org/TR/2012/WD-html-markup-20120329/input.url.html
