### ISSUE TITLE
Implement template for each widget from factory.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/form#158]

**Comment by terabytesoftw** [comment]
@Gerych1984

Your suggestion of template for each widget from the factory, thinking about it makes sense but we can simplify it, without affecting the widgets, which you think is this way of doing it:

`FieldAttributes.php`

```php
trait FieldAttributes
{
    private array $widgetTemplate = [];

    private function setWidgetTemplate(string $widgetClass): self
    {
        $new = clone $this;
        $new->template = $new->widgetTemplate[$widgetClass] ?? $new->template;
        return $new;
    }
}
```

`Field::php`

```php
final class Field extends Widget
{
    public function checkboxList(array $attributes = [], array $items = [], array $itemsFromValues = []): self
    {
        $new = clone $this;
        $new->setWidgetTemplate(CheckboxList::class);}
    }
}
```

Example config:

```php
Field::class => [
    'template()' => [
        '{label}<div class="col-sm-10">{input}{error}</div>'
    ],
   'widgetTemplate()`  =>[
       [
           CheckboxList::class => 'your template' // set your custom templete here
       ],
    ],
],
```

This should work without adding anything to each widget and without creating another widget.

**Comment by Gerych1984** [comment]
> @Gerych1984
> 
> Your suggestion #157 of template for each widget from the factory, thinking about it makes sense but we can simplify it, without affecting the widgets, which you think is this way of doing it:
> 
> `FieldAttributes.php`
> 
> ```
> trait FieldAttributes
> {
>     private array $widgetTemplate = [];
> 
>     private function setWidgetTemplate(string $widgetClass): self
>     {
>         $new = clone $this;
>         $new->template = $new->widgetTemplate[$widgetClass] ?? $new->template;
>         return $new;
>     }
> }
> ```
> 
> `Field::php`
> 
> ```
> final class Field extends Widget
> {
>     public function checkboxList(array $attributes = [], array $items = [], array $itemsFromValues = []): self
>     {
>         $new = clone $this;
>         $new->setWidgetTemplate(CheckboxList::class);
>     }
> }
> ```
> 
> Example config:
> 
> ```
> Field::class => [
>     'template()' => [
>         '{label}<div class="col-sm-10">{input}{error}</div>'
>     ],
>     'widgetTemplate()' =>[
>        [
>            CheckboxList::class => 'your template' // set your custom templete here
>        ],
>     ],
> ],
> ```
> 
> This should work without adding anything to each widget and without creating another widget.

My PR not pretended for last instance and could be improved. But few propose:

1. Save widgetTemplates and widgetTemlate separately (first can be used in widgets.php, second in current view for change/drop base template in current view file)
2. I think `setCurrentWidget` not works with that implementation. They should return string or pass current instance as argument. Another inner `$new` do nothing

**Comment by Gerych1984** [comment]
> @Gerych1984
> 
> Your suggestion 

And I it's are PR, with already works code, tests and phpdoc. Not issue or suggest. Little issue I will write on remark
