### ISSUE TITLE
FormModel trait

### ISSUE THREAD

**Issue by armpogart** [yiisoft/form#16]
What about adding a `FormModel` trait and leaving the abstract class also there (which will use the trait). I'm usually for using composition over inheritance.

Also this will allow us to decouple some parts: `FormTrait` and `FormValidationTrait` for use cases when I don't need validation for the form or I want to use some other library/logic for the validation.

**Comment by samdark** [comment]
Are FormTrait and FormValidationTrait usable separately? Are there forms where validation isn't needed?

**Comment by terabytesoftw** [comment]
I do not agree with traits with abstract classes, that is not the task of the form-model.

**Comment by armpogart** [comment]
@terabytesoftw traits will just ease the usage and will allow to extend the models from our own classes if there is a need. I don't see a particular reason here why trait with interface can't do the same as currently abstract class does. Any particular reason why you don't agree with traits? (P.S. I even agree that abstract class can be kept here for those who don't need trait).

@samdark Yes, the idea is to have them usable separately and the model (class) will just implement needed interfaces and use the traits. I'm not currently sure for the use case of the form where the validation is not needed, the only advantage I see there currently is one will be free to use other libraries or logic for validation. The **most** important use case for separating to 2 traits is when we need the model for API. In API we still separate db entities and API request/response DTOs, and in that case we need validation but we don't need all the stuff concerning directly forms (attribute labels, hints....). Current implementation forces us to have all the code anyway.

**Comment by terabytesoftw** [comment]
I clearly understand your idea of a minimal abstract class and traits that specifically extend the class, but I think it could make shapes more difficult, the idea being that they should be as simple as possible, I agree with @samdark that logic forms should be validations, if you want something else you can extend the class.

**Comment by armpogart** [comment]
@terabytesoftw What do you think about following?
> The most important use case for separating to 2 traits is when we need the model for API. In API we still separate db entities and API request/response DTOs, and in that case we need validation but we don't need all the stuff concerning directly forms (attribute labels, hints....). Current implementation forces us to have all the code anyway.

**Comment by samdark** [comment]
> I'm not currently sure for the use case of the form where the validation is not needed

Then it may be a hint that there are none.

> In API we still separate db entities and API request/response DTOs, and in that case we need validation but we don't need all the stuff concerning directly forms (attribute labels, hints....).

Attribute labels are still needed for user-friendly validation errors, even that's API, aren't they?

**Comment by armpogart** [comment]
> Attribute labels are still needed for user-friendly validation errors, even that's API, aren't they?
Why do I need attribute labels? They are not used in validation messages, I will just specify needed validations messages and if I need to somehow customize attribute names in JSON (as example) output I will just implement `JsonSerializable` interface.

**Comment by samdark** [comment]
It is not about names. It is about error messages. Usually these use attribute labels.

**Comment by samdark** [comment]
Had a chat today with another developer who's interested in being about not to inherit from base abstract class. They have a CMS and their own objects hierarchy.

**Comment by terabytesoftw** [comment]
After refactoring a `Trait Validator` makes sense, since you should be able to `model` and `form` only with `Validation HTML only`, and not make `Validator mandatory`, since you could use any, that would give more `abstraction to the forms`.
