### ISSUE TITLE
Change FormModel::attributes as protected or add method like getAttributeNames

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/form#161]
Good day. In my case i have `AbstractSearchForm` extends from `FormModel`. Today i need write base method `toArray` that returns array of filters like `[name => value, ....]` to store it in database. But i can't do it without reflection. So - as we have protected `collectAttributes` maybe set property `attributes` also protected? Or add method that return array of attribute names. Thanks

**Comment by samdark** [comment]
Check https://github.com/yiisoft/yii-middleware/blob/master/src/SubFolder.php.

**Comment by terabytesoftw** [comment]
Can you give an example of what you want to do since `collectAttributes()` returns all the attributes of the formModel:

https://github.com/yiisoft/form/blob/ebf4532dc40f005d016ca5c0dcf4de57e51ab237/src/FormModel.php#L250

**Comment by Gerych1984** [comment]
> Can you give an example of what you want to do since `collectAttributes()` returns all the attributes of the formModel:
> 
> https://github.com/yiisoft/form/blob/ebf4532dc40f005d016ca5c0dcf4de57e51ab237/src/FormModel.php#L250

My current realization (writed today) in `abstract class AbstractSearchForm extends FormModel`. I'm using this to send as **data** in Vue form component. Or store in DB - when user save selected filters to quick access in future

```
public function toArray(bool $hideEmpty = true): array
{
    $array = [];
    /**
     *I think need $this->attributes or sometihng like $this->getAttributeNames() instead of ReflctionClass/ReflectionProperty
    */
    $class = new ReflectionClass($this);
    $properties = $class->getProperties(ReflectionProperty::IS_PROTECTED | ReflectionProperty::IS_PUBLIC);

    foreach ($properties as $property) {
        if ($property->isStatic()) {
            continue;
        }

        $name = $property->getName();
        $value = $this->getAttributeValue($name);

        if ($value === null || is_scalar($value)) {
            if ($hideEmpty && ($value === '' || $value === null)) {
                continue;
            }

            $array[$name] = $value;
        } elseif (is_array($value)) {
            if ($hideEmpty && count($value) === 0) {
                continue;
            }

            $array[$name] = $value;
        } elseif ($value instanceof FormModel) {
            $nested = $value->toArray($hideEmpty);

            if ($hideEmpty && count($nested) === 0) {
                continue;
            }

            $array[$name] = $nested;
        }
    }

    return $array;
}
```

**Comment by terabytesoftw** [comment]
> > Can you give an example of what you want to do since `collectAttributes()` returns all the attributes of the formModel:
> > https://github.com/yiisoft/form/blob/ebf4532dc40f005d016ca5c0dcf4de57e51ab237/src/FormModel.php#L250
> 
> My current realization (writed today) in `abstract class AbstractSearchForm extends FormModel`. I'm using this to send as **data** in Vue form component. Or store in DB - when user save selected filters to quick access in future
> 
> ```
> public function toArray(bool $hideEmpty = true): array
> {
>     $array = [];
>     /**
>      *I think need $this->attributes or sometihng like $this->getAttributeNames() instead of ReflctionClass/ReflectionProperty
>     */
>     $class = new ReflectionClass($this);
>     $properties = $class->getProperties(ReflectionProperty::IS_PROTECTED | ReflectionProperty::IS_PUBLIC);
> 
>     foreach ($properties as $property) {
>         if ($property->isStatic()) {
>             continue;
>         }
> 
>         $name = $property->getName();
>         $value = $this->getAttributeValue($name);
> 
>         if ($value === null || is_scalar($value)) {
>             if ($hideEmpty && ($value === '' || $value === null)) {
>                 continue;
>             }
> 
>             $array[$name] = $value;
>         } elseif (is_array($value)) {
>             if ($hideEmpty && count($value) === 0) {
>                 continue;
>             }
> 
>             $array[$name] = $value;
>         } elseif ($value instanceof FormModel) {
>             $nested = $value->toArray($hideEmpty);
> 
>             if ($hideEmpty && count($nested) === 0) {
>                 continue;
>             }
> 
>             $array[$name] = $nested;
>         }
>     }
> 
>     return $array;
> }
> ```

Why do a `getAttributes()`, if calling `collectAttributes()` has the same attributes, i don't understand.
**https://github.com/yiisoft/form/blob/ebf4532dc40f005d016ca5c0dcf4de57e51ab237/src/FormModel.php#L38**

**Comment by Gerych1984** [comment]
> Why do a `getAttributes()`, if calling `collectAttributes()` has the same attributes, i don't understand.
> 
> https://github.com/yiisoft/form/blob/ebf4532dc40f005d016ca5c0dcf4de57e51ab237/src/FormModel.php#L38
> 
> ** **

It will be call twice (or N times) and unnecessary recalculate attribute types just for get names. I can call `collectAttributes` in `AbstractSearchModel::__construct`, but for what? We already have this array, maybe just add method like in AR 
```
public function attributes(): array
{  
    return array_keys($this->attributes);
}
```

**Comment by terabytesoftw** [comment]
> > Why do a `getAttributes()`, if calling `collectAttributes()` has the same attributes, i don't understand.
> > https://github.com/yiisoft/form/blob/ebf4532dc40f005d016ca5c0dcf4de57e51ab237/src/FormModel.php#L38
> 
> It will be call twice (or N times) and unnecessary recalculate attribute types just for get names. I can call `collectAttributes` in `AbstractSearchModel::__construct`, but for what? We already have this array, maybe just add method like in AR
> 
> ```
> public function attributes(): array
> {  
>     return array_keys($this->attributes);
> }
> ```

If now explained in that way it makes sense.
