### ISSUE TITLE
split package

### ISSUE THREAD

**Issue by thenotsoft** [yiisoft/form#23]
Split the package into 2 packages, place widgets in a separate package, for example form-widgets, because when using RestAPI widgets are not needed

**Comment by xepozz** [comment]
@samdark Can you please create a repo?

**Comment by samdark** [comment]
Name?

**Comment by xepozz** [comment]
form-widgets?

**Comment by samdark** [comment]
https://github.com/yiisoft/form-widgets/

**Comment by samdark** [comment]
Actually, it is better to use https://github.com/yiisoft/yii-widgets

**Comment by samdark** [comment]
https://github.com/yiisoft/request-model
