### ISSUE TITLE
Dependency update/adjust to yiisoft/html

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/form#234]
### What steps will reproduce the problem?

My composer use yiisoft/html v3.

### What is the expected result?

Composer update is success.

### What do you get instead?

Composer dependency problem:
    - yiisoft/form[dev-master, 1.0.x-dev] require yiisoft/html ^2.4 -> satisfiable by yiisoft/html[2.4.0, 2.5.0].

**Comment by samdark** [comment]
https://github.com/yiisoft/form/pull/232

**Comment by vjik** [comment]
Done. Now `"yiisoft/html": "^3.0",`
