### ISSUE TITLE
Nested array form with translations

### ISSUE THREAD

**Issue by kamilalterpage** [yiisoft/form#236]
Hi. I want to create nested array form with translation array.
Currently i can make input like AttributeValue['name.en'] (code below)
I want to create input name  like AttributeValue[{value_Id}]['name.en']
But the problem is that the TranslatableAttributeForm is not array, he contain only one value.

Is this possible to create two levels array form there?

```php
class ProductGroupValueEditForm extends BaseFormModel
{
    public ?string $system_name = null;

    public ?int $sequence = null;

    public TranslatableAttributeForm $name;


    public function getRules(): array
    {
        $rules = array_merge(parent::getRules(), [
            'system_name' => [new HasLength(max: 128, skipOnEmpty: true)],
        ]);

        foreach (LocaleHelper::getLanguages() as $language) {
            $rules['name.' . $language] = [new Required, new HasLength(max: 128)];
        }

        return $rules;
    }

    public function getAttributeLabels(): array
    {
        $translationLabels = (new ProductGroupValueTranslation())->attributeLabels();
        foreach (LocaleHelper::getLanguages() as $language) {
            foreach ($translationLabels as $attribute => $label) {
                $translationLabels["$attribute.$language"] = $label;
            }
        }

        return array_merge($translationLabels, (new ProductGroupValue())->attributeLabels());
    }
}
```

**Comment by vjik** [comment]
What is `TranslatableAttributeForm` ?

**Comment by kamilalterpage** [comment]
`final class TranslatableAttributeForm extends FormModel
{

    public ?string $pl = null;

    public ?string $en = null;

    public ?string $de = null;

    public ?string $ru = null;

    public ?string $fr = null;

    public ?string $es = null;


    public function getAttributeLabels(): array
    {
        return array_fill_keys(LocaleHelper::getLanguages(), '');
    }

}`

**Comment by vjik** [comment]
Are usage `AttributeValue['{value_Id}.name.en']` is resolve problem?
