### ISSUE TITLE
Add php attribute like #[SkipHydration] to skip private properties in collectAttributes()

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/form#263]
Is it possible?

https://github.com/yiisoft/form/blob/2cb6c8d2ad56249ed35530e8f8027f03e25dea50/src/FormModel.php#L211

#[SkipHydration]:
https://github.com/yiisoft/hydrator/blob/3bfa311986fccb929b39564ca19e0dbe4ea11662/src/Hydrator.php#L99

**Comment by vjik** [comment]
Use `\Yiisoft\Hydrator\Attribute\SkipHydration`.
