### ISSUE TITLE
Split FormModel to 2 classes (API models and Html form models)

### ISSUE THREAD

**Issue by armpogart** [yiisoft/form#35]
Split `FormModel` to 2 classes `RequestModel` or `Model` or `TransferObject` and `FormModel` which will extend from the first one. The first one will contain only logic necessary for API models stripping anything needed for Html forms.

**Comment by armpogart** [comment]
Also #16

**Comment by samdark** [comment]
Sounds like a good idea.

**Comment by xepozz** [comment]
@romkatsu did you complete work on `RequestModel`?

**Comment by romkatsu** [comment]
> @romkatsu did you complete work on `RequestModel`?
No, I'll get back to it soon

**Comment by romkatsu** [comment]
> > @romkatsu did you complete work on `RequestModel`?
> 
> No, I'll get back to it soon

should first wait for the completion of work on https://github.com/yiisoft/router/issues/57

**Comment by samdark** [comment]
Naming a class just `Model` caused confusion about MVC in the past. Many beginners thought that M is MVC is just a single "Model" class. Either we need to use more specific name or explain it in the docs. This package is "form" so for it being "form"-model sounds logical to me.

> This will reduce code duplication in the code.

I'm not sure it is a good idea to reuse a single "model" for both API and HTML form. It is likely that API and HTML form will diverge and you'll have to make changes in one place causing issues in another place.

**Comment by samdark** [comment]
Closing since we have https://github.com/yiisoft/request-model
