### ISSUE TITLE
How to deal with empty string in number form field?

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/form#356]
### What steps will reproduce the problem?

Try to render `Field::number(()` with empty string as value.

### What is the expected result?

Input field was rendered.

### What do you get instead?

_InvalidArgumentException
Number field requires a numeric or null value._

From `\Yiisoft\Form\Field\Number::generateInput()`

### Additional info

HTML form always sends values as string - so writing additional code to converts `''` to `null` is annoying.

Hmm... something like this is possible?
https://github.com/yiisoft/form/blob/master/src/Field/Number.php#L175
```
if ($value !== '' && !is_numeric($value) && $value !== null) {
    throw new InvalidArgumentException('Number field requires a numeric or null value.');
}
```

| Q                | A
| ---------------- | ---
| Version          | dev-master
| PHP version      | 8.2

**Comment by tomaszkane** [comment]
`\Yiisoft\Form\Field\Number` is also `final` so it cannot be extend to override `generateInput`.
Maybe this class can be replaced via DI/config plugin/Theme ?

**Comment by vjik** [comment]
> `\Yiisoft\Form\Field\Number` is also `final` so it cannot be extend to override `generateInput`. Maybe this class can be replaced via DI/config plugin/Theme ?

This should be improved in package.
