### ISSUE TITLE
Form validation scenarios

### ISSUE THREAD

**Issue by armpogart** [yiisoft/form#36]
Do we something similar to scenarios from yii2?

I'm all for specialized DTO projections, such as `UserCreateDto`, `UserUpdateDto`, but maybe someone will find it more productive to have one model with conditional validation for such cases. I see it as simply different groups of validators for each named scenario.

**Comment by samdark** [comment]
I'm against scenarios. These caused really fat form/AR models in Yii 2 and I think it will be the same in Yii 3 if we'll add them.

**Comment by armpogart** [comment]
@samdark Ok, I just opened the issue for any possible discussion. I would try to contribute the usage of specialized DTOs for such cases.
