### ISSUE TITLE
Implement a simple mapper in the package

### ISSUE THREAD

**Issue by armpogart** [yiisoft/form#37]
It would be helpful if the package will also provide simple mapper/automapper for mapping `FormModel` attributes to Entity and vice-versa. This can be useful for both API models and Html form models.

**Comment by samdark** [comment]
How would you configure it?

**Comment by armpogart** [comment]
We will configure some mapper/automapper in container by giving it mappings. If the names of the properties are the same it would be enough and it will allow also extended configuration.

Example from other library (there are multiple php mappers, the basic one will be built-in to the package) :
```php
$config = new AutoMapperConfig();

// Simply registering the mapping is enough to convert properties with the same
// name. Custom actions can be registered for each individual property.
$config
    ->registerMapping(Employee::class, EmployeeDto::class)
    ->forMember('age', function (Employee $source) {
        return date('Y') - $source->getBirthYear();
    })
    ->reverseMap(); // Register the reverse mapping as well.
                            
$mapper = new AutoMapper($config);

// With this configuration we can start converting our objects.
$john = new Employee(10, "John", "Doe", 1980);
$dto = $mapper->map($john, EmployeeDto::class);

echo $dto->firstName; // => "John"
echo $dto->lastName; // => "Doe"
echo $dto->age; // => 37
```

**Comment by samdark** [comment]
Can't you, instead, add the following to your custom form model:

```php
final class PersonForm extends FormModel
{
    // usual form stuff

    public function getDto(): Person
    {
        $person= new Person();
        $person->firstName = $this->firstName;
        $person->lastName = $this->lastName;
        $person->age = date('Y') - $this->birthYear;
        return $person;
    }
}
```

That's only 6 lines compared to about 10 lines of configuring a mapper...

**Comment by armpogart** [comment]
@samdark First of all you will also need the reverse one, so your code example will be larger. Second I am always recommending to do something you mentioned when just starting the project and you are not sure how big your entity and models will grow, how complex they will become, and how many of the you will have. But as practice shows it is a way more convenient to use some sort of automapper for projects with a lot of entity -> model mappings. And in case if you do the same thing with reverse and for a few model -> entity mappings, your code will be to long compared to configuring just automapper (take into account that you initialize mapper just ones and then configure only mappings, which will be just one line for simple models). I'm just proposing to have simple mapper built-in to the package (that will work flawlessly with our model) and not recommending to always use it by default.

If you think that the mapper is out of context of this package, we can simply document the possibility of using one of the mappers already available.

**Comment by samdark** [comment]
Alright. I forgot about reverse mapping. It makes sense overall.

**Comment by armpogart** [comment]
Also mapper will help with nested forms (the implementation of nested forms #43). The code becomes very complicated when doing it manually in these cases.

**Comment by arogachev** [comment]
This can be related:

- https://github.com/yiisoft/validator/issues/77
- https://github.com/yiisoft/validator/pull/175

**Comment by vjik** [comment]
Done via hydrator usage.
