### ISSUE TITLE
Virtual property

### ISSUE THREAD

**Issue by xepozz** [yiisoft/form#39]
I think would be great to have ability to use virtual property.
By virtual property I mean ability to `Form` to have getter without having property with similar name.
For example:
```php
class Form {
  private string $_requestId;

  public function getRequestId() {
    return $this->_requestId;
  }
  // or
  private string $request_id;

  public function getRequestId() {
    return $this->request_id;
  }
  // or
  public function getRequestId() {
    return $this->myCoolProperty;
  }
}
```
Discussion was started [here](https://github.com/yiisoft/form/pull/38#discussion_r470770432)

**Comment by samdark** [comment]
How would you use such feature?

**Comment by samdark** [comment]
Closing since:

1. There seem to be no use-case.
2. Currently you can create a property no matter if you use it in the form or not, you can also read and write it with `getAttributeValue()` and `setAttributeValue()`.
