### ISSUE TITLE
Fix load to remove hiddenInput from fileInput

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/form#41]
As described [here](https://github.com/yiisoft/form/blob/master/src/Widget/FileInput.php#L41), a hidden input is added to support cases where fileInput is the only field of the form. I'm not sure how this works, but I will take that information for granted.
Since _most_ forms with a file input will also have other fields, wouldn't it make more sense to have it default to NOT adding a hidden input and enable it explicitely if required?

**Comment by samdark** [comment]
We are [using form prefix](https://github.com/yiisoft/form/blob/master/src/FormModel.php#L83). Fields are named like `Contact[message]`, `Contact[email]` and end up in an array in `$_POST`:

```php
[
    'Contact' => [
        'message' => 'Hello!',
        'email' => 'hello@example.com',
    ]
]
```

File input doesn't cause `$_POST` to be filled at all i.e. it is empty regardless if file was submitted or not so for a form with a file input only this check won't pass:

https://github.com/yiisoft/form/blob/master/src/FormModel.php#L153

That's why we are submitting hidden input.

**Comment by Mister-42** [comment]
> a form with a file input only this check won't pass

That is an exception, as most forms will have multiple fields. For this exception, `withHiddenInput` is left intact.

It seems logical to me to have the default options match the most common scenarios. I would agree that needs documentation though.

**Comment by samdark** [comment]
A form with file upload only is quite common so there are multiple ways to solve it:

1. Do not do anything. User doesn't have to do anything. Works out of the box.
2. Allow disabling hidden inputs but don't touch defaults. User doesn't have to do anything. Works out of the box. Can be manually turned off for a specific form.
3. Modify the check in `load()` method to take uploaded files into account. Remove hidden inputs.

**Comment by Mister-42** [comment]
I don't deny _quite common_, but it's not __most__ common.

1. Does not produce clean code by default, because _sometimes_ it is needed.
2. idem
3. This makes sense.

With the logic you apply to this field it would make sense to add `enctype="multipart/form-data"` to every post form, because sometimes it is needed and users don't have to do anything.

**Comment by samdark** [comment]
Yii 2 adds `enctype="multipart/form-data"` automatically when file input is added: https://github.com/yiisoft/yii2/blob/23a8d041a6867090d95df9051b294dcc73f50b7e/framework/widgets/ActiveField.php#L482

**Comment by Mister-42** [comment]
I know, but we are not dealing with Yii 2 here

**Comment by samdark** [comment]
Well then, overall, I think we need to implement point 3 and remove hidden inputs at all.
