### ISSUE TITLE
HiddenInput is not always completely hidden

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/form#74]
### What steps will reproduce the problem?
Have `enclosedByContainer` defined, like [this](https://github.com/yiisoft/yii-bootstrap5/blob/master/config/params.php)

`echo $field->config($form, 'example')->hiddenInput();`

### What is the expected result?
`<input type="hidden" id="form-example" class="form-control" name="Form[example]">`

### What do you get instead?
```
<div class="form-group field-form-example mb-3">

<input type="hidden" id="form-example" class="form-control" name="Form[example]">

</div>
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 8.0.2
| Operating system | Debian 10

**Comment by samdark** [comment]
Do you mean that `<div class="form-group field-form-example mb-3">` is not what is hidden?

**Comment by Mister-42** [comment]
A div can contain padding, colors, borders and even content from css. Not exactly my idea of hidden :)

I have seen a lot of Yii 2 Issues before from people complaining about the Label not being hidden. I think we should start off correctly now 👍🏻

**Comment by terabytesoftw** [comment]
This behavior is expected because you are building it inside `Field::class`, where everything is wrapped in a div, now with the new `PR` you can change the tag, even delete it, but by default it is the right thing to do if you want a field hidden will just use `Hidden::class`.

**Comment by samdark** [comment]
https://github.com/yiisoft/form/pull/86
