### ISSUE TITLE
Adding more form adaptions from rules

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/form#76]
Creating new issue so this won't get lost.

`textarea` can have `minlength` and `maxlength`
Required is also available for `select`, `textarea`
Besides `number` and `email`, input can also be `url` (among other things, but those do not have a validator in Yii. Not sure if that would be viable to implement).

---

### Need more research:
~`pattern` vs [RegularExpression](https://github.com/yiisoft/validator/blob/master/src/Rule/MatchRegularExpression.php)~ Already taken care of, I totally missed that :)
`step` - not a validation option in Yii

_Originally posted by @Mister-42 in https://github.com/yiisoft/form/issues/65#issuecomment-767014816_

**Comment by terabytesoftw** [comment]
The validator should not change the attributes of the forms.

**Comment by samdark** [comment]
@terabytesoftw I disagree. HTML validation attributes are alright to be generated based on validators configured.

**Comment by terabytesoftw** [comment]
> @terabytesoftw I disagree. HTML validation attributes are alright to be generated based on validators configured. At least it is very convenient and allows to keep HTML-based validation and server validation in sync.

For example, if you use the `required` attribute and in turn use the `Required::rule()` validator, the form will only show the error of the `HTML validator browser`, it will never show the error of the `Yii3 Validator`, what is the point of doing a double validation here?

**Comment by samdark** [comment]
1. Benefit of having validation on the client side is to avoid extra form submits and get the validation result ASAP.
2. But that doesn't eliminate the need for server validation since one can easily modify HTML before submitting the form.

**Comment by terabytesoftw** [comment]
> 1. Benefit of having validation on the client side is to avoid extra form submits and get the validation result ASAP.
> 2. But that doesn't eliminate the need for server validation since one can easily modify HTML before submitting the form.

Ok I think I can implement them without needing the interfaces to wrap the validator, would you agree to remove them?

**Comment by samdark** [comment]
@terabytesoftw depends on the implementation.
