### ISSUE TITLE
Ability to prevent encoding of label in Yiisoft\Form\Widget\Label

### ISSUE THREAD

**Issue by hyncica** [yiisoft/form#85]
Currently it is hard to prevent encoding of label by Label widget.
For example if your label contains entity for non-breaking space:
In model class:
```php
 public function getAttributeLabels(): array
{
    return [
        'myField' => 'My&nbsp;Field',
    ];
}
```
Then when you use it like this it will be double encoded:
```php
Label::widget()->config($model, 'myField');
```
Currently, I've found a workaround to prevent double encoding like this:
```php
class NoEncodeString implements \Yiisoft\Html\NoEncodeStringableInterface
{
    private string $value = '';

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}

Label::widget()->config($model, 'myField', ['label' => new NoEncodeString($model->getAttributeLabel('myField'))]);
```

Problem with this workaround is, that the label must be passed into widget only this way. The instance of NoEncodeString cannot be used inside model's `getAttributeLabels()` because the `getAttributeLabel()` method return type is `string`.
It also cannot be passed to widget's `label()` method because its parameter is hinted as `string` type so it's converted when the method is called.

The easiest solution would be to add a method/option to `Label` that would prevent encoding the label when building the html tag.
The more generic solution might be to make `\Yiisoft\Html\NoEncodeStringableInterface` extend the `\Stringable` interface and use `string|Stringable` instead of `string` type whenever string is passing through method to be used later.

**Comment by samdark** [comment]
https://github.com/yiisoft/html/issues/76

**Comment by terabytesoftw** [comment]
In the `PR` it is proposed to turn off the coding for the widgets from `Field::class` just like this:

Widget code:
```php
Field::widget()->config($this->formModel, 'string')->label(['label' => 'My&nbsp;Field', 'encode' => false])->render();
```

Output HTML:
```HTML
<div>
<label for="typeform-string">My&nbsp;Field</label>
</div>
```
