### ISSUE TITLE
Behavior of the Validator on the forms.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/form#87]
The validator should not change the attributes of the forms, i propose that the attributes of  `HTML` can be added independently of the validator, since they are two different validations, one by the browser, and the other with `FormModel::class`, they must be independent one of the other, using both for the same validation does not make sense.

**Comment by samdark** [comment]
I disagree since logically the rules for both validations are the same.

**Comment by samdark** [comment]
See https://github.com/yiisoft/form/issues/76#issuecomment-899046899
