### ISSUE TITLE
Radio & RadioList Widgets casting value to int

### ISSUE THREAD

**Issue by beastbytes** [yiisoft/form#97]
### Steps to reproduce problem
In a view:
<?= Field::widget()->config($form, 'os')->radioList([], ['android' => 'Android', 'ios' => 'iOS', 'pureos' => 'PureOS']) ?>

Where $form::os = 'ios'

### Expected result
```html
<div>
    <label for="myform-os">OS</label>
    <div id="myform-os">
        <label><input type="radio" name="MyForm[os]" value="android"> Android</label>
        <label><input type="radio" name="MyForm[os]" value="ios" checked> iOS</label>
        <label><input type="radio" name="MyForm[os]" value="pureos"> PureOS</label>
    </div>
</div>
```

### Actual result
The iOS radio input is not checked
```html
<div>
    <label for="myform-os">OS</label>
    <div id="myform-os">
        <label><input type="radio" name="MyForm[os]" value="android"> Android</label>
        <label><input type="radio" name="MyForm[os]" value="ios"> iOS</label>
        <label><input type="radio" name="MyForm[os]" value="pureos"> PureOS</label>
    </div>
</div>
```
### Cause
Yiisoft\Form\Widget\RadioList line 227 casts the existing value to int (the same is done at Yiisoft\Form\Widget\Radio line 110).

### Fix
Remove casting to int

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev-master
| PHP version      | 8.0.11
| Operating system | Ubuntu 20.04

**Comment by vjik** [comment]
This should be a simple change in `Yiisoft\Form\Widget\RadioList`. @beastbytes, care to propose a PR?
